#Workflow Name
name: ApplyGrid CI

#Events
on:
  push:
    branches:
      - main
#Jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node version
        run: node --version

      - name: npm version
        run: npm --version

      - name: Docker version
        run: docker --version

      - name: Docker Compose version
        run: docker compose version
