#Workflow Name
name: ApplyGrid CI

#Events
on:
  push:
    branches:
      - main
#Jobs
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Where am I?
        run: pwd

      - name: What is this machine?
        run: uname -a

      - name: Who am I?
        run: whoami

      - name: List files
        run: ls -la
