name: Secrets Experiment

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret
        env:
          TEST_SECRET: ${{ secrets.MY_TEST_SECRET }}
        run: echo "Secret length is ${#TEST_SECRET}"
